import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Users list app",
  description: "Generated by create next app",
};

export default function TodoLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <section className="bg-slate-800 h-screen text-slate-100 container mx-auto p-4">
      {children}
    </section>
  );
}
